apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demosite-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fabioandreola/argocd-demo.git
    targetRevision: HEAD
    path: apps/demosite
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true