apiVersion: v1
kind: Service
metadata:
  name: demosite
  labels:
    app: demosite
    service: demosite
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: demosite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite
  labels:
    app: demosite
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demosite
      version: blue
  template:
    metadata:
      labels:
        app: demosite
        version: blue
    spec:
      containers:
      - name: demosite
        image: fabioandreola/demosite:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000